export const generatePrelude = () => [
    `  ;; Prelude`,
    `  (import "wasi_snapshot_preview1" "fd_write"`,
    `    (func $fd_write (param i32 i32 i32 i32) (result i32)))`,
    ``,
    `    (func $log (param $string_idx i32)`,
    `       local.get $string_idx`,
    `       i32.const 4`,
    `       i32.add`,
    `       (i32.store (i32.const 1000))`,
    `       local.get $string_idx`,
    `       i32.load`,
    `       (i32.store (i32.const 1004))`,
    `       i32.const 1`,
    `       i32.const 1000`,
    `       i32.const 1`,
    `       i32.const 1008`,
    `       call $fd_write`,
    `       drop)`,
    `\n`
].join('\n');
